// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Board: typeof import('./src/components/Board.vue')['default']
    BoardHeader: typeof import('./src/components/BoardHeader.vue')['default']
    EmojiDropdown: typeof import('./src/components/EmojiDropdown.vue')['default']
    EmojiPanel: typeof import('./src/components/EmojiPanel.vue')['default']
    MarkdownPreviewer: typeof import('./src/components/MarkdownPreviewer.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    MessageSkeleton: typeof import('./src/components/MessageSkeleton.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NH1: typeof import('naive-ui')['NH1']
    NH3: typeof import('naive-ui')['NH3']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NNumberAnimation: typeof import('naive-ui')['NNumberAnimation']
    NPagination: typeof import('naive-ui')['NPagination']
    NResult: typeof import('naive-ui')['NResult']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    NThing: typeof import('naive-ui')['NThing']
    ReplyForm: typeof import('./src/components/ReplyForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
